namespace:
  name: sandbox
 
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: micweber/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 64m
    memory: 250Mi
  limits:
    cpu: 128m
    memory: 500Mi

ports:
  containerPort: 3111

livenessProbe:
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz
  port: 3111
